title: Swirledup
subtitle: My take on Diy's,Thoughts, and ideas
cover_image: "https://images.unsplash.com/photo-1441803293480-6d6c52f377d9?auto=format&fit=crop&w=1050&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D"

author: Nesa Shamdasani
profile_image:
url: "/"
name: Nesa Shamdasani
bio: Welecome! I am so excited to see you. I hope you enjoy my diy's, thoughts on different opinions, and ideas. 

email: nesaprincess@gmail.com 

description: > # this means to ignore newlines until the next setting
  I am a 11 year old swirler. Join me in my adventure through this totaly swirled up world. 
  Comment and give feedback as you look though my world.  
  So, what are we waiting for,  let's get swirled!


permalink: /:year/:month/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      class_name: "post-template"
  -
    scope:
      path: ""
      type: "pages"
    values:
      class_name: "page-template"

# Build settings
markdown: kramdown
theme: caspertwo
exclude:
  - Gemfile
  - Gemfile.lock
